# This `flake.nix` was generated by running:
#
#     nix run home-manager/release-25.11 -- init --switch --impure
#
# Make sure `$HOME/.config/nix/nix.conf` contains the following line:
#
#     experimental-features = nix-command flakes
#
# https://nix-community.github.io/home-manager/index.xhtml#sec-flakes-standalone
{
  description = "Home Manager configuration of christoph";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { nixpkgs, home-manager, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in
    {
      homeConfigurations."christoph" = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;

        modules = [ ./home.nix ];
      };
    };
}
